name: Geração Automática do Gráfico Pacman

on:
  schedule:
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  gerar_grafico_pacman:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Criar pasta dist
        run: mkdir -p dist
      
      - name: Gerar gráfico de contribuições estilo Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Enviar gráfico para a branch 'output-pacman'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-pacman
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
